name: Security Audit

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
      - name: Install dependencies
        run: |
          gem install bundler-audit
          bundle install
      - name: Run bundler-audit
        run: bundler-audit check --update
